# Generated by Django 5.1.15 on 2026-06-13 07:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lng_planner", "0005_customerschedule_supplierschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierschedule",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="preference",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="to_date",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="to_date",
        ),
        migrations.CreateModel(
            name="CustomerDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_ranges",
                        to="lng_planner.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["from_date"],
            },
        ),
        migrations.CreateModel(
            name="Refinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "daily_refinery_supply",
                    models.FloatField(
                        help_text="MT per day",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refineries",
                        to="lng_planner.plant",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refineries",
                        to="lng_planner.simulation",
                    ),
                ),
            ],
            options={
                "ordering": ["plant__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="RefineryDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_ranges",
                        to="lng_planner.refinery",
                    ),
                ),
            ],
            options={
                "ordering": ["from_date"],
            },
        ),
        migrations.CreateModel(
            name="SimulationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="lng_planner.simulation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_ranges",
                        to="lng_planner.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["from_date"],
            },
        ),
        migrations.DeleteModel(
            name="CustomerSchedule",
        ),
        migrations.DeleteModel(
            name="SupplierSchedule",
        ),
    ]
